---
title: "Visualization Exercises"
author: "Sarah Greenwood"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r cars}
library(tidyverse)
library(gapminder)
data(gapminder)
```

## Exercise: Make a Line Plot

```{r gapminder}
plot(x=gapminder$year[gapminder$country == "Afghanistan"],
     y=gapminder$pop[gapminder$country == "Afghanistan"], 
     type = "l")
```

```{r}
gapminder %>% 
  filter(country == "Afghanistan") %>%
  ggplot(aes(x = year, y = pop)) + 
  geom_line()
```

## Exercise: Histogram

```{r}
gapminder %>% 
  filter(year == "2007") %>%
  ggplot(aes(x = lifeExp)) + 
  geom_histogram(bins = 40) #this is where you change the number of bins
```

## `ggplot` Exercise: Change Colors

```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
gapminder %>%
  filter(year==2002) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, colour = factor(continent))) + # adds color!
  geom_point() + 
  scale_x_log10() + # this transforms the data
  scale_color_manual(values = cbPalette)
```

## `ggplot` Exercise: Multiple lines and facets

```{r}
gapminder %>%
  ggplot(aes(x = year, y = lifeExp, by = country, color = continent)) + 
  geom_line() +
  geom_point() + 
  facet_grid(continent ~ . )
  
```

# `ggplot` Exercise: Add a Trend Line

```{r}
gapminder %>%
  filter(year == "2007") %>%
  ggplot(aes(y=lifeExp, x=pop, color=continent)) + 
  geom_point() + 
  scale_x_log10() + 
  geom_smooth(method = lm)

```

```{r}
gapminder %>%
  filter(year == "2007") %>%
  ggplot(aes(y=lifeExp, x=pop)) + 
  geom_point() + 
  scale_x_log10() + 
  geom_smooth(method = lm)
```


# More exercises 

```{r}
library(babynames)
data(babynames)
```

```{r}
babynames <- mutate(babynames, initial = substr(name, 1,1))

initial_props <-
  babynames %>%
  group_by(year, sex, initial) %>%
  summarize(count = sum(n), totalprop = sum(prop)) %>%
  ungroup()

topnames <- babynames %>% 
  filter(year>=1950) %>% 
  group_by(name) %>% 
  summarize(total=sum(n)) %>%
  arrange(desc(total)) %>%
  head(1000) %>%
  inner_join(babynames) %>%
  filter(year >= 1950) %>%
  mutate(sex=recode(sex, "F"="Female", "M"="Male")) %>%
  group_by(name, sex, total) %>%
  summarize(sextotal=sum(n)) %>%
  spread(key=sex, value=sextotal) %>%
  mutate(ratio=(Male-Female)/total)

```

```{r}
filter(initial_props, initial %in% c("A","E","I","O","U","Y")) %>% 
  mutate(sex=factor(sex, levels=c("F","M"), labels=c("Female", "Male"))) %>%
  ggplot(aes(y=totalprop, x=year, color=initial)) +
  geom_line() + 
  facet_wrap(~sex) +
  labs(title="Baby Names First Initial", x="Year", y="Proportion of Babies") +
  scale_color_discrete(name="First Initial") +
  theme(axis.text.x = element_text(angle = -90, vjust=.5))
```





